// Input data types (from JSON files generated by data collection scripts)
export type TokenManagerMigrationData = {
    environment: string;
    network: string;
    stargateNFTAddress: string;
    nodeManagementV3Address: string;
    migrations: TokenMigrationEntry[];
};

export type TokenMigrationEntry = {
    tokenId: number;
    owner: string;
    tokenManager: string;
};

// Output data types (for migration execution results)
export type MigrationExecutionReport = {
    environment: string;
    network: string;
    stargateNFTAddress: string;
    timestamp: string;
    totalMigrations: number;
    successfulMigrations: number;
    failedMigrations: number;
    results: TokenMigrationResult[];
};

export type TokenMigrationResult = {
    tokenId: number;
    tokenManager: string;
    txHash?: string;
    status: "success" | "error";
    blockNumber?: number;
    error?: string;
    dryRun?: boolean;
};
